### ISSUE TITLE
[Bug] UnshieldSharp "Failed to read header files" for specific archives

### ISSUE THREAD

**Issue by TheRogueArchivist** [mnadareski/UnshieldSharp#11]
UnshieldSharp "Failed to read header files" for specific archives. The archives present in "sdcc_200.zip" from "CICA 32 For Windows CD-ROM (Walnut Creek) (October 1999) (Disc 4).iso" in https://archive.org/details/CICA_32_For_Windows_CD-ROM_Walnut_Creek_October_1999 are known to be affected. Further debugging is needed.

**Comment by TheRogueArchivist** [comment]
Several installers in http://redump.org/disc/78048/ also exhibit what seems to be this same bug.

**Comment by mnadareski** [comment]
Should be fixed as of https://github.com/mnadareski/UnshieldSharp/commit/262b2917e571a35b585536c4db45fccc3d19db06

**Comment by TheRogueArchivist** [comment]
Can confirm that the primary issue was fixed in 262b2917e571a35b585536c4db45fccc3d19db06.
