### ISSUE TITLE
US# does not extract all of multi-file archive

### ISSUE THREAD

**Issue by TheRogueArchivist** [mnadareski/UnshieldSharp#6]
I've got an archive that goes up to data4.cab, and US# does not seem to be completely extracting it. The combine filesize of the archives is 1.7 GB, while only around 0.8 GB is extracted. There is an error trying to extract a specific file. 

``Outputting file at index 111 to C:\Users\silas\Downloads\0beyond\data1\sally_clean.bf...
Decompression failed with code -3. bytes_to_read=26088, volume_bytes_left=681968940, volume=2, read_bytes=26089``

**Comment by mnadareski** [comment]
Currently resolved due to https://github.com/mnadareski/UnshieldSharp/commit/89ee01d3de1aad09a6cd94bc0bdc1396af69eb96
